goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/<slug:subcategory_slug>', views.CatalogView.as_view(), name='search'),
    path('filter-products-by-type/', views.TypeFilterView.as_view(), name='filter_products_by_type'),
    path('<slug:subcategory_slug>', views.CatalogView.as_view(), name='index'),
    path('product/<slug:product_article>', views.ProductView.as_view(), name='product'),
    path('categories/', views.CategoriesView.as_view(), name='categories'),
    path('subcategories/<slug:category_slug>', views.SubcategoriesView.as_view(), name='subcategories'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about', views.AboutView.as_view(), name='about'),
    path('project', views.ProjectView.as_view(), name='project'),
]

musshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from musshop import settings
from main.views import page_not_found, server_error
from .settings import DEBUG


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='order')),
]

handler404 = page_not_found
handler500 = server_error

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if DEBUG:
#     urlpatterns += [
#         path('__debug__/', include('debug_toolbar.urls')),
#     ]

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.CreateOrderView.as_view(), name='create_order'),
    path('order-history/', views.OrderHistoryView.as_view(), name='order_history'),
    path('order-detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('order-delete/<int:order_id>/', views.OrderDeleteView.as_view(), name='order_delete'),
]

orders/models.py
from django.core.validators import RegexValidator

from django.db import models

from goods.models import Products
from users.models import User


class OrderitemQueryset(models.QuerySet):
   
    def total_price(self):
        return sum(cart.products_price() for cart in self)
   
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class DeliveryMethod(models.Model):
    name = models.CharField(max_length=100, verbose_name="Способ доставки")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Стоимость доставки", default=0)
    required_address = models.BooleanField(default=False, verbose_name="Требуется адрес доставки")
    is_active = models.BooleanField(default=True, verbose_name="Доступна ли опция")

    class Meta:
        verbose_name = "Способ доставки"
        verbose_name_plural = "Способы доставки"

    def __str__(self):
        return f"{self.name} ({self.price} ₽)"
    
class Order(models.Model):
    phoneNumberRegex = RegexValidator(regex=r"^((\+7|7|8)+([0-9]){10})$")

    class StatusChoices(models.TextChoices):
        PROCESSING = 'processing', 'В обработке'
        CONFIRMED = 'confirmed', 'Принят в работу'
        COMPLETED = 'completed', 'Выполнен'
        CANCELED = 'canceled', 'Отменен'

    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа" )
    phone_number = models.CharField(validators=[phoneNumberRegex], max_length=12)
    email = models.EmailField(max_length=50, verbose_name="Email")
    delivery_method = models.ForeignKey(to=DeliveryMethod, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="Способ доставки")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    delivery_comment = models.TextField(null=True, blank=True, verbose_name="Комментарии к доставке")
    payment_on_get = models.BooleanField(default=False, verbose_name="Оплата при получении")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(
        max_length=20,
        choices=StatusChoices.choices,
        default=StatusChoices.PROCESSING,
        verbose_name="Статус заказа"
    )

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        ordering = ("id",)

    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"

    def get_status_display(self):
        return self.StatusChoices(self.status).label

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"
        ordering = ("id",)

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

orders/forms.py
from django import forms

from orders.models import DeliveryMethod

from common.filters import clean_phone

class UserInfoForm(forms.Form):
    first_name = forms.CharField(label='Имя*')
    last_name = forms.CharField(label='Фамилия*')
    phone_number = forms.CharField(label='Номер телефона*')
    email = forms.EmailField(label='Email*')

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number', '')
        return clean_phone(phone_number)

class DeliveryForm(forms.Form):
    delivery_method = forms.ModelChoiceField(
        queryset=DeliveryMethod.objects.none(),
        widget=forms.RadioSelect,
    )
    delivery_address = forms.CharField(label='Адрес доставки', required=False)
    delivery_comment = forms.CharField(label='Комментарии к доставке', required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        queryset = self.fields['delivery_method'].queryset = DeliveryMethod.objects.filter(is_active=True)

        try:
            pickup_option = queryset.get(name__iexact='Самовывоз')
            self.fields['delivery_method'].initial = pickup_option
        except DeliveryMethod.DoesNotExist:
            pass

    def clean(self):
        cleaned_data = super().clean()

        delivery_method = cleaned_data.get("delivery_method")
        delivery_address = cleaned_data.get("delivery_address")

        if delivery_method and delivery_method.price > 0 and not delivery_address:
            self.add_error("delivery_address", "Укажите адрес доставки.")

class PaymentForm(forms.Form):
    payment_on_get = forms.ChoiceField(choices=[
            ("0", False),
            ("1", True),
        ],
        initial="0",
        widget=forms.RadioSelect
    )

orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.core.exceptions import ValidationError
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import DeleteView, DetailView, ListView
from django.contrib import messages

from carts.models import Cart
from orders.models import Order, OrderItem
from .models import DeliveryMethod

from .forms import UserInfoForm, DeliveryForm, PaymentForm

class CreateOrderView(LoginRequiredMixin, View):
    template_name = 'orders/create_order.html'

    # вызов шаблона
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(request)
        context['title'] = 'Оформление заказа'
        context['body_class'] = 'checkout_page'

        return render(request, self.template_name, context)
    
    # обработка заказа
    def post(self, request, *args, **kwargs):
        user = request.user
        user_info, delivery_info, payment_info = self.get_forms(request.POST)
    
        if not self.forms_are_valid(user_info, delivery_info, payment_info):
            return JsonResponse({
                'success': False,
                'user_errors': user_info.errors,
                'delivery_errors': delivery_info.errors,
                'payment_errors': payment_info.errors,
            }, status=400)
        
        try:
            self.create_order(user, user_info, delivery_info, payment_info)
            messages.success(self.request, "Заказ успешно оформлен. Спасибо за покупку!")
            return JsonResponse({'redirect_url': reverse('orders:order_history')})
        except ValidationError as e:
            return JsonResponse({'success': False, 'message_ajax': e.message}, status=400)

    # формирование данных для шаблона
    def get_context_data(self, request):
        user = request.user
        delivery_options = DeliveryMethod.objects.all().order_by('id')
        del_price = DeliveryMethod.objects.filter(name='Доставка').first().price if DeliveryMethod.objects.filter(name='Доставка').exists() else None

        default_delivery = DeliveryMethod.objects.filter(name="Самовывоз", is_active=True).first()
        default_delivery_id = default_delivery.id if default_delivery else None

        initial = {
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email,
            'phone_number': user.phone_number
        }

        return {
            'delivery_options': delivery_options,
            'del_price': del_price,
            'default_delivery_id': default_delivery_id,
            'user_info': UserInfoForm(initial=initial),
            'delivery_info': DeliveryForm(),
            'payment_info': PaymentForm(),
        }
    
    # создание форм
    def get_forms(self, data):
        return UserInfoForm(data), DeliveryForm(data), PaymentForm(data)
    
    # проверка валидности всех форм
    def forms_are_valid(self, *forms):
        return all([form.is_valid() for form in forms])
    
    # создание заказа и его элементов
    def create_order(self, user, user_info, delivery_info, payment_info):
        cart_items = Cart.objects.filter(user=user)

        if not cart_items.exists():
            raise ValidationError("Корзина пуста.")

        with transaction.atomic():
            order = Order.objects.create(
                user=user,
                phone_number=user_info.cleaned_data['phone_number'],
                email=user_info.cleaned_data['email'],
                delivery_method=delivery_info.cleaned_data['delivery_method'],
                delivery_address=delivery_info.cleaned_data['delivery_address'],
                delivery_comment=delivery_info.cleaned_data['delivery_comment'],
                payment_on_get=payment_info.cleaned_data['payment_on_get'],
            )

            for cart_item in cart_items:
                product = cart_item.product

                if product.quantity < cart_item.quantity:
                    raise ValidationError(f'Недостаточно товара "{product.name}" в наличии.')
                            
                OrderItem.objects.create(
                    order=order,
                    product=product,
                    name=product.name,
                    price=product.sell_price(),
                    quantity=cart_item.quantity,
                )

                product.quantity -= cart_item.quantity
                product.save()

            cart_items.delete()

        return order

class OrderHistoryView(LoginRequiredMixin, ListView):
    template_name = 'orders/order_history.html'
    context_object_name = 'orders'
    paginate_by = 3

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user).order_by('-created_timestamp')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'История заказов'
        context['body_class'] = 'shop_page'
        return context

class OrderDetailView(LoginRequiredMixin, DetailView):
    template_name = 'orders/order_detail.html'
    context_object_name = 'order'

    def get_object(self, queryset = None):
        order = get_object_or_404(Order, id=self.kwargs.get('order_id'))
        return order
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = self.object
        order_items = OrderItem.objects.filter(order=order)
        items_sum = sum(order_item.price * order_item.quantity for order_item in order_items)
        context['title'] = f'Заказ № {order.id}'
        context['order_items'] = order_items
        context['items_sum'] = items_sum
        return context

class OrderDeleteView(LoginRequiredMixin, DeleteView):
    model = Order
    pk_url_kwarg = 'order_id'
    success_url = reverse_lazy('orders:order_history')

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, status='processing')
    
    def form_valid(self, form):
        order_id = self.get_object().id
        response = super().form_valid(form)
        messages.success(self.request, f"Заказ №{order_id} успешно удалён.")
        return response

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}
{% load phone_tags %}

{% block content %}

    <!-- Ec breadcrumb start -->
    {% block breadcrumb %}
        {% include "includes/breadcrumb.html" %}
    {% endblock  %}
    <!-- Ec breadcrumb end -->
 
    <!-- Ec checkout page -->
    <section class="ec-page-content section-space-p">
        <div class="container">
            <div class="row">
                <div class="ec-checkout-leftside col-lg-8 col-md-12 ">
                    <!-- checkout content Start -->
                    <div class="ec-checkout-content">
                        <div class="ec-checkout-inner">
                            <div class="ec-checkout-wrap margin-bottom-30">
                                {% user_carts request as carts %}
                                {% include "carts/includes/included_cart.html" %}
                            </div>
                            <div class="ec-checkout-wrap margin-bottom-30 padding-bottom-3">
                                <div class="ec-checkout-block ec-check-bill">
                                    <h3 class="ec-checkout-title">Детали заказа</h3>
                                    <div class="ec-bl-block-content">
                                    
                                        <div class="ec-check-bill-form">
                                            <form action="{% url 'orders:create_order' %}" method="post" id="id_user_info_form">
                                                {% csrf_token %}
                                                <span class="ec-bill-wrap ec-bill-half">
                                                    <label for="id_first_name">{{ user_info.first_name.label }}</label>
                                                    <input type="text" 
                                                        id="id_first_name"
                                                        value="{% if user_info.first_name.value %}{{ user_info.first_name.value }}{% endif %}"
                                                        name="first_name"
                                                        placeholder="Введите имя..." required />
                                                </span>
                                                <span class="ec-bill-wrap ec-bill-half">
                                                    <label for="id_last_name">{{ user_info.last_name.label }}</label>
                                                    <input type="text" name="last_name"  id="id_last_name" 
                                                        value="{% if user_info.last_name.value %}{{ user_info.last_name.value }}{% endif %}"  
                                                        placeholder="Введите фамилию..." required />
                                                </span>
                                                <span class="ec-bill-wrap" id="id_delivery_address_field">
                                                    <label>{{ delivery_info.delivery_address.label }}</label>
                                                    <input type="text" name="delivery_address" id="id_delivery_address"
                                                    value="{% if delivery_info.delivery_address.value %}{{ delivery_info.delivery_address.value }}{% endif %}"    
                                                    placeholder="Введите адрес..." required />
                                                    <div class="alert alert-danger alert-dismissible fade show" style="display: none" id="delivery_address_error">Введите адрес доставки</div>
                                                </span>
                                                <span class="ec-bill-wrap ec-bill-half">
                                                    <label for="id_email">{{ user_info.email.label }}</label>
                                                    <input type="email" id="id_email"
                                                    name="email"
                                                    value="{% if user_info.email.value %}{{ user_info.email.value }}{% endif %}"
                                                    placeholder="Введите email..." />
                                                </span>
                                                <span class="ec-bill-wrap ec-bill-half">
                                                    <label for="id_phone_number">{{ user_info.phone_number.label }}</label>
                                                    <input type="text" id="id_phone_number"
                                                    name="phone_number"
                                                    value="{% if user_info.phone_number.value %}{{ user_info.phone_number.value|format_phone_tag }}{% else %}+7({% endif %}"
                                                    required />
                                                    <div class="alert alert-danger alert-dismissible fade show" style="display: none" id="phone_number_error">Неверный формат номера</div>
                                                </span>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <span class="ec-check-order-btn">
                                <button type="submit" class="btn btn-primary" id="id_create_order_button">Оформить заказ</button>
                            </span>
                        </div>
                    </div>
                    <!--cart content End -->
                </div>
                <!-- Sidebar Area Start -->
                <div class="ec-checkout-rightside col-lg-4 col-md-12">
                    <div class="ec-sidebar-wrap">
                        <!-- Sidebar Summary Block -->
                        <div class="ec-sidebar-block">
                            <div class="ec-sb-title">
                                <h3 class="ec-sidebar-title">Итог</h3>
                            </div>
                            <div class="ec-sb-block-content">
                                <div class="ec-checkout-summary">
                                    {% include "carts/includes/total.html" %}
                                </div>
                            </div>
                        </div>
                        <!-- Sidebar Summary Block -->
                    </div>
                    <div class="ec-sidebar-wrap ec-checkout-del-wrap">
                        <!-- Sidebar Summary Block -->
                        <div class="ec-sidebar-block">
                            <div class="ec-sb-title">
                                <h3 class="ec-sidebar-title">Способ получения</h3>
                            </div>
                            <div class="ec-sb-block-content">
                                <div class="ec-checkout-del">
                                    <div class="ec-del-desc">Пожалуйста, выберите способ получения.</div>
                                    <form action="{% url 'orders:create_order' %}" method="post" id="id_delivery_form">
                                        {% csrf_token %}
                                        <span class="ec-del-option">
                                            {% if delivery_options %}
                                                {% for delivery_option in delivery_options %}
                                                <span>
                                                    {% if delivery_option.is_active == False %}

                                                        <span class="ec-del-opt-head" style="opacity: 0.5;">{{ delivery_option.name }}</span>
                                                        <span style="opacity: 0.5;">(недоступно)</span>
                                                        <input style="opacity: 0.5;" type="radio" id="{{ delivery_option.id }}" data-option="{{ delivery_option.required_address }}"
                                                            value="{{ delivery_option.id }}"
                                                            name="delivery_method"
                                                            disabled>
                                                        <label style="opacity: 0.5;" for="{{ delivery_option.id }}">{{ delivery_option.price }} ₽</label>
                                                    
                                                    {% else %}
                                                    
                                                        <span class="ec-del-opt-head">{{ delivery_option.name }}</span>
                                                        <input type="radio" id="{{ delivery_option.id }}" data-option="{{ delivery_option.required_address }}"
                                                            value="{{ delivery_option.id }}"
                                                            name="delivery_method"
                                                            {% if delivery_option.id == default_delivery_id %}checked{% endif %}>
                                                        <label for="{{ delivery_option.id }}">{{ delivery_option.price }} ₽</label>

                                                    {% endif %}
                                                </span>
                                                {% endfor %}
                                            {% else %}
                                                <span class="ec-del-opt-head">Выбор способа получения пока недоступен</span>
                                            {% endif %}
                                        </span>
                                        <span class="ec-del-commemt">
                                            <span class="ec-del-opt-head">{{ delivery_info.delivery_comment.label }}</span>
                                            <textarea name="delivery_comment" id="id_delivery_comment"
                                            value="{% if delivery_info.delivery_comment.value %}{{ delivery_info.delivery_comment.value }}{% endif %}"
                                            placeholder="Комментарий..."></textarea>
                                        </span>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <!-- Sidebar Summary Block -->
                    </div>
                    <div class="ec-sidebar-wrap ec-checkout-pay-wrap">
                        <!-- Sidebar Payment Block -->
                        <div class="ec-sidebar-block">
                            <div class="ec-sb-title">
                                <h3 class="ec-sidebar-title">Способ оплаты</h3>
                            </div>
                            <div class="ec-sb-block-content">
                                <div class="ec-checkout-pay">
                                    <div class="ec-pay-desc">Пожалуйста, выберите способ оплаты.</div>
                                    <form action="{% url 'orders:create_order' %}" method="post" id="id_payment_form">
                                        <span class="ec-pay-option">
                                            <span>
                                                <input type="radio" id="id_payment_on_get" name="payment_on_get" value="0" checked>
                                                <label for="id_payment_on_get">Оплата при получении</label>
                                            </span>
                                            <span>
                                                <input type="radio" id="id_payment_on_cart" name="payment_on_get" value="1">
                                                <label for="id_payment_on_cart">Оплата картой</label>
                                            </span>
                                        </span>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}