carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.CartAddView.as_view(), name='cart_add'),
    path('cart_change/', views.CartChangeView.as_view(), name='cart_change'),
    path('cart_remove/', views.CartRemoveView.as_view(), name='cart_remove'),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/<slug:subcategory_slug>', views.CatalogView.as_view(), name='search'),
    path('filter-products-by-type/', views.TypeFilterView.as_view(), name='filter_products_by_type'),
    path('<slug:subcategory_slug>', views.CatalogView.as_view(), name='index'),
    path('product/<slug:product_article>', views.ProductView.as_view(), name='product'),
    path('categories/', views.CategoriesView.as_view(), name='categories'),
    path('subcategories/<slug:category_slug>', views.SubcategoriesView.as_view(), name='subcategories'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about', views.AboutView.as_view(), name='about'),
    path('project', views.ProjectView.as_view(), name='project'),
]

musshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from musshop import settings
from main.views import page_not_found, server_error
from .settings import DEBUG


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='order')),
]

handler404 = page_not_found
handler500 = server_error

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if DEBUG:
#     urlpatterns += [
#         path('__debug__/', include('debug_toolbar.urls')),
#     ]

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.CreateOrderView.as_view(), name='create_order'),
    path('order-history/', views.OrderHistoryView.as_view(), name='order_history'),
    path('order-detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('order-delete/<int:order_id>/', views.OrderDeleteView.as_view(), name='order_delete'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('users-cart/', views.UsersCartView.as_view(), name='users_cart'),
    path('wishlist/', views.WishlistView.as_view(), name='wishlist'),
    path('wishlist-add/', views.WishlistAddView.as_view(), name='wishlist_add'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
]

carts/models.py
from django.db import models

from users.models import User
from goods.models import Products

class CartQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_base_price(self):
        return sum(cart.products_base_price() for cart in self)
    
    def discount_amount(self):
        return self.total_base_price() - self.total_price()

    def total_quantity(self): 
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class Cart(models.Model):

    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Пользователь')
    session_key = models.CharField(max_length=32,  blank=True, null=True)
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    class Meta:
        db_table = 'cart'
        verbose_name = "Корзина"
        verbose_name_plural = "Корзина"
        ordering = ("id",)

    objects = CartQueryset().as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)
    
    def products_base_price(self):
        return round(self.product.price * self.quantity, 2)

    def __str__(self):
        if self.user:
            return f'Корзина {self.user.username} | Товар {self.product.name} | Количество {self.quantity}'
        
        return f'Анонимная корзина | Товар {self.product.name} | Количество {self.quantity}'

carts/views.py
from django.http import JsonResponse
from django.views import View

from carts.models import Cart
from carts.utils import get_user_carts
from carts.mixins import CartMixin

from goods.models import Products


class CartAddView(CartMixin, View):
    def post(self, request):
        product_id = request.POST.get("product_id")
        product_qty = request.POST.get("product_qty")
        product = Products.objects.get(id=product_id)

        cart = self.get_cart(request, product=product)

        if product_qty:
            qty = int(product_qty)
        else:
            qty = 1

        if cart:
            cart.quantity += qty
            cart.save()
        else:
            Cart.objects.create(user=request.user if request.user.is_authenticated else None,
                session_key=request.session.session_key if not request.user.is_authenticated else None,
                product=product, quantity=qty)
            
        response_data = {
            "qty": qty,
            "message_ajax": "Товар добавлен в корзину",
            "cart_items_html": self.render_cart(request).get('cart_items_html'),
            "modal_cart_items_html": self.render_cart(request).get('modal_cart_items_html'),
        }
        
        return JsonResponse(response_data)

class CartChangeView(CartMixin, View):
    def post(self, request):
        cart_id = request.POST.get("cart_id")
        cart = self.get_cart(request, cart_id=cart_id)
        message_ajax = ""

        if cart:
            cart.quantity = request.POST.get("quantity")
            cart.save()
            quantity = cart.quantity
        else:
            quantity = 0
            message_ajax = "Позиция ранее уже была удалена"

        response_data = {
            "quantity": quantity,
            "qty": get_user_carts(request).total_quantity(),
            "cart_items_html": self.render_cart(request).get('cart_items_html'),
            "modal_cart_items_html": self.render_cart(request).get('modal_cart_items_html'),
            "total": self.render_cart(request).get('total'),
            "message_ajax": message_ajax
        }

        return JsonResponse(response_data)

class CartRemoveView(CartMixin, View):
    def post(self, request):
        cart_id = request.POST.get("cart_id")
        cart = self.get_cart(request, cart_id=cart_id)

        if cart:
            cart.quantity = request.POST.get("quantity")
            cart.delete()
            quantity = cart.quantity
            message_ajax = "Товар удален из корзины"
        else:
            quantity = 0
            message_ajax = "Позиция ранее уже была удалена"

        response_data = {
            "quantity": quantity,
            "qty": get_user_carts(request).total_quantity(),
            "cart_items_html": self.render_cart(request).get('cart_items_html'),
            "modal_cart_items_html": self.render_cart(request).get('modal_cart_items_html'),
            "total": self.render_cart(request).get('total'),
            "message_ajax": message_ajax
        }

        return JsonResponse(response_data)

carts/templates/carts/includes/included_cart.html
{% load static %}

<div class="ec-cart-content">
    <div class="ec-cart-inner">
        {% if carts %}
        <div class="row">
            <form action="">
                <div class="table-content cart-table-content">
                    <table>
                        <thead>
                            <tr>
                                <th>Товар</th>
                                <th>Цена</th>
                                <th style="text-align: center;">Количество</th>
                                <th>Итого</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cart in carts %}
                            <tr>
                                <td data-label="Product" class="ec-cart-pro-name"><a
                                        href="{% url "catalog:product" cart.product.article %}"><img class="ec-cart-pro-img mr-4"
                                        {% if cart.product.images.first.image.url %}
                                            style="width: 70px; height: 70px; object-fit: contain"
                                            src="{{ cart.product.images.first.image.url }}"
                                        {% else %}
                                            src="{% static "assets/images/product-image/1.jpg" %}"
                                        {% endif %}
                                            alt="{{ cart.product.name }}" />{{ cart.product.name }}</a></td>
                                <td data-label="Price" class="ec-cart-pro-price">
                                    {% if cart.product.discount %}
                                    <s>{{ cart.product.price }} ₽</s><br>
                                        <span class="amount">{{ cart.product.sell_price }} ₽</span>
                                    {% else %}
                                        <span class="amount">{{ cart.product.price }} ₽</span>
                                    {% endif %}
                                </td>
                                {% if show_btn %}
                                <td data-label="Quantity" class="ec-cart-pro-qty"
                                    style="text-align: center;">
                                    <div class="cart-qty-plus-minus">
                                        <input class="cart-plus-minus" type="text"
                                            name="cartqtybutton" 
                                            data-cart-id="{{ cart.id }}" 
                                            data-cart-change-url="{% url 'cart:cart_change' %}" 
                                            value="{{ cart.quantity }}" 
                                            readonly />
                                            {% csrf_token %}
                                        <div class="ec_cart_qtybtn">
                                            <div class="inc ec_qtybtn">+</div>
                                            <div class="dec ec_qtybtn">-</div>
                                        </div>
                                    </div>
                                </td>
                                {% else %}
                                 <td data-label="Quantity" class="ec-cart-pro-subtotal" style="text-align: center;">
                                    {{ cart.quantity }} шт.
                                </td>
                                {% endif %}
                                <td data-label="Total" class="ec-cart-pro-subtotal">{{ cart.products_price }} ₽</td>
                                {% if show_btn %}
                                <td data-label="Remove" class="ec-cart-pro-remove">
                                    <a href="{% url "cart:cart_remove" %}" class="remove-from-cart" 
                                    data-cart-id="{{ cart.id }}">
                                    {% csrf_token %}
                                    <i class="ecicon eci-trash-o"></i></a>
                                </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="ec-cart-update-bottom">
                            <a href="{% url "catalog:categories" %}">Продолжить покупки</a>
                            {% if show_btn %}
                            <a href="{% url "orders:create_order" %}" class="btn btn-primary text-white text-decoration-none">Оформить заказ</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </form>
        </div>
        {% else %}
            <p class="emp-cart-msg">Ваша корзина пуста</p>
            <a class="btn btn-primary" href="{% url "catalog:categories" %}">Начать покупки</a>
        {% endif %}
    </div>
</div>

carts/templates/carts/includes/modal_cart.html
{% load static %}

<div class="ec-cart-inner">
    <div class="ec-cart-top">
        <div class="ec-cart-title">
            <span class="cart_title">Корзина</span>
            <button class="ec-close">×</button>
        </div>
        {% if carts %}
        <ul class="eccart-pro-items">
            {% for cart in carts %}
            <li>
                <a href="{% url "catalog:product" cart.product.article %}" class="sidekka_pro_img">
                    {% if cart.product.images.first.image.url %}
                        <img src="{{ cart.product.images.first.image.url }}" style="width: 70px; height: 70px; object-fit: contain" alt="{{ cart.product.name }}">
                    {% else %}
                        <img src="{% static "assets/images/product-image/6_1.jpg" %}" alt="{{ cart.product.name }}">
                    {% endif %}
                </a>
                <div class="ec-pro-content">
                    <a href="{% url "catalog:product" cart.product.article %}" class="cart_pro_title">{{ cart.product.name }}</a>
                    <span class="cart-price">
                    {% if cart.product.discount %}
                        <s>{{ cart.product.price }} ₽</s><br>
                        <span>{{ cart.product.sell_price }}</span>
                    {% else %}
                        <span>{{ cart.product.price }} ₽</span>
                    {% endif %} 
                    x {{ cart.quantity }}</span>
                    <div class="qty-plus-minus">
                        <div class="dec ec_qtybtn">-</div>
                        <input class="qty-input" type="text" 
                        name="ec_qtybtn" 
                        data-cart-id="{{ cart.id }}" 
                        data-cart-change-url="{% url 'cart:cart_change' %}" 
                        value="{{ cart.quantity }}" 
                        readonly/>
                        {% csrf_token %}
                        <div class="inc ec_qtybtn">+</div>
                    </div>
                    <a href="{% url "cart:cart_remove" %}" class="remove remove-from-cart"
                    data-cart-id="{{ cart.id }}"
                    data-qty="{{ cart.quantity }}">
                    {% csrf_token %}×</a>
                </div>
            </li>
            {% endfor %}
        </ul>
        {% else %}
            <p class="emp-cart-msg">Ваша корзина пуста</p>
            <a class="btn btn-primary" href="{% url "catalog:categories" %}">Начать покупки</a>
        {% endif %}
    </div>
    {% if carts %}
    <div class="ec-cart-bottom">
        <div class="cart-sub-total">
            <table class="table cart-table">
                <tbody>
                    <tr>
                        <td class="text-left">Цена без учёта скидки:</td>
                        <td class="text-right">{{ carts.total_base_price }} ₽</td>
                    </tr>
                    {% if  carts.discount_amount %}
                    <tr>
                        <td class="text-left">Скидка:</td>
                        <td class="text-right">-{{ carts.discount_amount }} ₽</td>
                    </tr>
                    {% endif %}
                    <tr>
                        <td class="text-left">Итог:</td>
                        <td class="text-right primary-color">{{ carts.total_price }} ₽</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="cart_btn">
            <a href="{% url "users:users_cart" %}" class="btn btn-primary">Подробнее</a>
            <a href="{% url "orders:create_order" %}" class="btn btn-secondary">Заказать</a>
        </div>
    </div>
    {% endif %}
</div>

carts/templates/carts/includes/total.html
<div>
    <span class="text-left">Цена без учёта скидки:</span>
    <span class="text-right">{{ carts.total_base_price }} ₽</span>
</div>
{% if  carts.discount_amount %}
<div>
    <span class="text-left">Скидка:</span>
    <span class="text-right">-{{ carts.discount_amount }} ₽</span>
</div>
{% endif %}
{% if not show_btn %}
    {% if del_price %}
        <div id="id_plus_delivery" data-delivery="{{ del_price }}">
            <span class="text-left">Доставка:</span>
            <span class="text-right">{{ del_price }} ₽</span>
        </div>
    {% else %}
        <span class="text-right">0 ₽</span>
    {% endif %}
{% endif %}

<div class="ec-cart-summary-total">
    <span class="text-left">Итог:</span>
    <span class="text-right" id="id_total_price" data-price="{{ carts.total_price }}">{{ carts.total_price }} ₽</span>
</div>