carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.CartAddView.as_view(), name='cart_add'),
    path('cart_change/', views.CartChangeView.as_view(), name='cart_change'),
    path('cart_remove/', views.CartRemoveView.as_view(), name='cart_remove'),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/<slug:subcategory_slug>', views.CatalogView.as_view(), name='search'),
    path('filter-products-by-type/', views.TypeFilterView.as_view(), name='filter_products_by_type'),
    path('<slug:subcategory_slug>', views.CatalogView.as_view(), name='index'),
    path('product/<slug:product_article>', views.ProductView.as_view(), name='product'),
    path('categories/', views.CategoriesView.as_view(), name='categories'),
    path('subcategories/<slug:category_slug>', views.SubcategoriesView.as_view(), name='subcategories'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about', views.AboutView.as_view(), name='about'),
    path('project', views.ProjectView.as_view(), name='project'),
]

musshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from musshop import settings
from main.views import page_not_found, server_error
from .settings import DEBUG


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='order')),
]

handler404 = page_not_found
handler500 = server_error

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if DEBUG:
#     urlpatterns += [
#         path('__debug__/', include('debug_toolbar.urls')),
#     ]

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.CreateOrderView.as_view(), name='create_order'),
    path('order-history/', views.OrderHistoryView.as_view(), name='order_history'),
    path('order-detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('order-delete/<int:order_id>/', views.OrderDeleteView.as_view(), name='order_delete'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('users-cart/', views.UsersCartView.as_view(), name='users_cart'),
    path('wishlist/', views.WishlistView.as_view(), name='wishlist'),
    path('wishlist-add/', views.WishlistAddView.as_view(), name='wishlist_add'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from django.core.validators import RegexValidator


class User(AbstractUser):
    phoneNumberRegex = RegexValidator(regex=r"^((\+7|7|8)+([0-9]){10})$")
    phone_number = models.CharField(validators=[phoneNumberRegex], max_length=12, blank=True, null=True)

    class Meta:
        db_table = 'User'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username
    
class Wishlist(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name="wishlist_items", verbose_name='Пользователь')
    product = models.ForeignKey(to='goods.Products', on_delete=models.CASCADE, verbose_name='Товар')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    class Meta:
        db_table = 'wishlist'
        verbose_name = "Избранное"
        verbose_name_plural = "Избранное"
        ordering = ("id",)
        
        constraints = [
            models.UniqueConstraint(fields=['user', 'product'], name='unique_user_product')
        ]

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from django.forms import fields

from users.models import User

from common.filters import clean_phone

class UserLoginForm(AuthenticationForm):

    class Meta: 
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()

class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "phone_number",
            "password1",
            "password2",
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    phone_number = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number', '')
        return clean_phone(phone_number)
    
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "phone_number",
        )

    first_name = forms.CharField(label="Имя")
    last_name = forms.CharField(label="Фамилия")
    username = forms.CharField(label="Логин")
    email = forms.CharField(label="Email")
    phone_number = forms.CharField(label="Номер телефона")

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number', '')
        return clean_phone(phone_number)

users/views.py
from django.contrib.auth.views import LoginView
from django.db import transaction
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse, reverse_lazy
from django.contrib import auth, messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.template.loader import render_to_string
from django.contrib.auth.views import LogoutView

from django.views.generic import CreateView, ListView, TemplateView, UpdateView

from carts.models import Cart
from goods.models import Products
from users.models import Wishlist

from users.forms import UserLoginForm, UserRegistrationForm, UserUpdateForm

from users.utils import get_wishlist_count, get_user_wishlist

class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm

    def get_success_url(self):
        redirect_page = self.request.POST.get('next', None)
        if redirect_page and redirect_page != reverse('user:logout'):
            return redirect_page
        return reverse_lazy('user:profile')
    
    def form_valid(self, form):
        session_key = self.request.session.session_key
        user = form.get_user()

        if user:
            auth.login(self.request, user)

            if session_key:
                new_carts = Cart.objects.filter(session_key=session_key)
                old_carts = Cart.objects.filter(user=user)
                
                for cart in new_carts:
                    existing_cart = old_carts.filter(product=cart.product).first()

                    if existing_cart:
                        existing_cart.quantity += cart.quantity
                        existing_cart.save()
                        cart.delete()
                    else:
                        cart.user = user
                        cart.session_key = None
                        cart.save()

            messages.success(self.request, f"{user.username}, Вы вошли в аккаунт")
            return HttpResponseRedirect(self.get_success_url())
        
    def form_invalid(self, form):
        messages.error(self.request, "Пользователь не найден")
        return super().form_invalid(form)
    
            
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация'
        return context

class UserRegistrationView(CreateView):
    template_name = 'users/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('user:profile')

    @transaction.atomic
    def form_valid(self, form):
        session_key=self.request.session.session_key
        user = form.instance

        if user:
            form.save()
            auth.login(self.request, user)
        if session_key:
            Cart.objects.filter(session_key=session_key).update(user=user, session_key=None)
            
        messages.success(self.request, f"{user.username}, Вы успешно зарегистрировались и вошли в аккаунт")
        return HttpResponseRedirect(self.success_url)
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        return context

class UserProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/profile.html'
    form_class = UserUpdateForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        form.save()
        if self.request.headers.get("x-requested-with") == "XMLHttpRequest":
            messages.success(self.request, f"{self.request.user.username}, Вы успешно обновили профиль")
            return JsonResponse({'success': True})
        return super().form_valid(form)

    def form_invalid(self, form):
        if self.request.headers.get("x-requested-with") == "XMLHttpRequest":
            return JsonResponse({'success': False, 'errors': form.errors}, status=400)
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Профиль пользователя'
        context['body_class'] = 'shop_page'
        return context

class UsersCartView(LoginRequiredMixin, TemplateView):
    template_name = 'users/users_cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Корзина'
        context['show_btn'] = True
        return context

class WishlistAddView(View):
    def post(self, request):
        user = request.user
        if user.is_authenticated:
            product_id = request.POST.get("product_id")
            product = Products.objects.get(id=product_id)
            in_wishlist = request.POST.get("in_wishlist").lower() == "true"
            if not in_wishlist:
                Wishlist.objects.create(user=user, product=product)
                response_data = {
                    'success': True,
                    'message_ajax': "Товар добавлен в избранное",
                    'wishlist_count': get_wishlist_count(request)
                }
            else:
                Wishlist.objects.filter(user=user, product=product).delete()
                wishlist_products = get_user_wishlist(request)
                wishlist_items_html = render_to_string(
                "users/includes/wishlist_items.html", {"wishlist_products": wishlist_products}, request=request)

                response_data = {
                    'success': True,
                    'message_ajax': "Товар удален из избранного",
                    'wishlist_count': get_wishlist_count(request),
                    'wishlist_items_html': wishlist_items_html
                }
        else:
            response_data = {
                'success': False,
                'message_ajax': "Пожалуйста, авторизируйтесь"
            }
        return JsonResponse(response_data)

class WishlistView(LoginRequiredMixin, ListView):
    template_name = 'users/wishlist.html'
    context_object_name = 'wishlist_products'
    paginate_by = 3

    def get_queryset(self):
        return Wishlist.objects.filter(user=self.request.user).order_by('-created_timestamp')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Избранное'
        return context

class CustomLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        username = request.user.username 
        messages.success(request, f"{username}, Вы вышли из аккаунта")
        return super().dispatch(request, *args, **kwargs)

users/templates/users/includes/edit_modal.html
{% load static %}
{% load phone_tags %}
<!-- Modal -->
<div class="modal fade" id="edit_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row">
                    <div class="ec-vendor-block-img space-bottom-30">
                        <div class="ec-vendor-block-detail">
                            <div class="thumb-upload">
                                <div class="thumb-edit">
                                    <input type='file' id="thumbUpload02" class="ec-image-upload"
                                        accept=".png, .jpg, .jpeg" />
                                    <label><img src= "{% static "assets/images/icons/edit.svg" %}"
                                            class="svg_img header_svg" alt="edit" /></label>
                                </div>
                            </div>
                        </div>
                        <div class="ec-vendor-upload-detail">
                            <form id="updateForm" class="row g-3" method="post" action="{% url 'users:profile' %}">
                                {% csrf_token %}
                                <div class="col-md-12 space-t-15">
                                    <label class="form-label">{{ form.username.label }}</label>
                                    <input type="text" name="username" id="id_username"
                                    value="{% if form.username.value %}{{ form.username.value }}{% endif %}" 
                                    class="form-control">
                                </div>
                                <div class="col-md-6 space-t-15">
                                    <label class="form-label">{{ form.first_name.label }}</label>
                                    <input type="text" name="first_name" id="id_first_name"
                                    value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                    class="form-control">
                                </div>
                                <div class="col-md-6 space-t-15">
                                    <label class="form-label">{{ form.last_name.label }}</label>
                                    <input type="text" name="last_name" id="id_last_name"
                                    value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" 
                                    class="form-control">
                                </div>
                                <div class="col-md-6 space-t-15">
                                    <label class="form-label">{{ form.email.label }}</label>
                                    <input type="text" name="email" id="id_email"
                                        value="{% if form.email.value %}{{ form.email.value }}{% endif %}" 
                                        class="form-control">
                                </div>
                                <div class="col-md-6 space-t-15">
                                    <label class="form-label">{{ form.phone_number.label }}</label>
                                    <input type="text" name="phone_number" id="id_phone_number"
                                        value="{% if form.phone_number.value %}{{ form.phone_number.value|format_phone_tag }}{% endif %}" 
                                        class="form-control">
                                </div>
                                <div class="col-md-12 space-t-15">
                                    <button type="submit" class="btn btn-primary">Обновить</button>
                                    <a href="#" class="btn btn-lg btn-secondary
                                        qty_close"
                                        data-bs-dismiss="modal"
                                        aria-label="Close">Закрыть</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal end -->

users/templates/users/includes/sidebar.html
<div class="ec-shop-leftside ec-vendor-sidebar col-lg-3 col-md-12">
    <div class="ec-sidebar-wrap">
        <!-- Sidebar Category Block -->
        <div class="ec-sidebar-block">
            <div class="ec-vendor-block">
                <div class="ec-vendor-block-items">
                    <ul>
                        <li><a href="{% url "users:profile" %}">Профиль</a></li>
                        <li><a href="{% url "users:wishlist" %}">Избранное</a></li>
                        <li><a href="{% url "orders:order_history" %}">История заказов</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

users/templates/users/includes/wishlist_items.html
{% load static %}

<table class="table ec-table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Изображение</th>
            <th scope="col">Наименование</th>
            <th scope="col">Стоимость</th>
            <th scope="col">Наличие</th>
            <th scope="col">Действия</th>
        </tr>
    </thead>
    <tbody class="wish-empt">
        {% if wishlist_products %}
            {% for wishlist_product in wishlist_products %}
            <tr class="pro-gl-content">
                <th scope="row"><span>{{ forloop.counter }}</span></th>
                <td class="prod_block">
                    <img class="prod_image" src="{% if wishlist_product.product.images.first.image.url %}{{wishlist_product.product.images.first.image.url}}{% else %}{% static "assets/images/product-image/1.jpg" %}{% endif %}"
                        alt="{{ wishlist_product.product.name }}">
                </td>
                <td><span><a href="{% url "catalog:product" wishlist_product.product.article %}">{{ wishlist_product.product.name }}</span></td>
                <td><span>{{ wishlist_product.price }}</span></td>
                <td><span class="avl">{% if wishlist_product.product.quantity > 0 %}В наличии {% else %} Нет в наличии {% endif %}</span></td>
                <td><span class="tbl-btn">
                    <div class="ec-pro-actions">
                        <a class="btn btn-lg btn-primary add-to-cart" data-product-id="{{ wishlist_product.product.id }}" 
                            href="{% url "cart:cart_add" %}" title="Добавить в корзину">{% csrf_token %}
                            <img src="{% static "assets/images/icons/pro_cart.svg" %}" class="svg_img pro_svg" alt="" />
                        </a>
                    </div>
                    <a class="btn btn-lg btn-primary ec-com-remove ec-remove-wish" 
                        data-product-id="{{ wishlist_product.product.id }}" 
                        data-in-wishlist="true"
                        data-url="{% url 'user:wishlist_add' %}"
                        title="Удалить из избранного">×</a></span>
                </td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="6">В избранном нет товаров</td>
            </tr>
        {% endif %}
    </tbody>
</table>