goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/<slug:subcategory_slug>', views.CatalogView.as_view(), name='search'),
    path('filter-products-by-type/', views.TypeFilterView.as_view(), name='filter_products_by_type'),
    path('<slug:subcategory_slug>', views.CatalogView.as_view(), name='index'),
    path('product/<slug:product_article>', views.ProductView.as_view(), name='product'),
    path('categories/', views.CategoriesView.as_view(), name='categories'),
    path('subcategories/<slug:category_slug>', views.SubcategoriesView.as_view(), name='subcategories'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about', views.AboutView.as_view(), name='about'),
    path('project', views.ProjectView.as_view(), name='project'),
]

musshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from musshop import settings
from main.views import page_not_found, server_error
from .settings import DEBUG


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='order')),
]

handler404 = page_not_found
handler500 = server_error

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if DEBUG:
#     urlpatterns += [
#         path('__debug__/', include('debug_toolbar.urls')),
#     ]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('users-cart/', views.UsersCartView.as_view(), name='users_cart'),
    path('wishlist/', views.WishlistView.as_view(), name='wishlist'),
    path('wishlist-add/', views.WishlistAddView.as_view(), name='wishlist_add'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from django.core.validators import RegexValidator


class User(AbstractUser):
    phoneNumberRegex = RegexValidator(regex=r"^((\+7|7|8)+([0-9]){10})$")
    phone_number = models.CharField(validators=[phoneNumberRegex], max_length=12, blank=True, null=True)

    class Meta:
        db_table = 'User'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username
    
class Wishlist(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name="wishlist_items", verbose_name='Пользователь')
    product = models.ForeignKey(to='goods.Products', on_delete=models.CASCADE, verbose_name='Товар')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    class Meta:
        db_table = 'wishlist'
        verbose_name = "Избранное"
        verbose_name_plural = "Избранное"
        ordering = ("id",)
        
        constraints = [
            models.UniqueConstraint(fields=['user', 'product'], name='unique_user_product')
        ]

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from django.forms import fields

from users.models import User

from common.filters import clean_phone

class UserLoginForm(AuthenticationForm):

    class Meta: 
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()

class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "phone_number",
            "password1",
            "password2",
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    phone_number = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number', '')
        return clean_phone(phone_number)
    
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "phone_number",
        )

    first_name = forms.CharField(label="Имя")
    last_name = forms.CharField(label="Фамилия")
    username = forms.CharField(label="Логин")
    email = forms.CharField(label="Email")
    phone_number = forms.CharField(label="Номер телефона")

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number', '')
        return clean_phone(phone_number)

users/views.py
from django.contrib.auth.views import LoginView
from django.db import transaction
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse, reverse_lazy
from django.contrib import auth, messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.template.loader import render_to_string
from django.contrib.auth.views import LogoutView

from django.views.generic import CreateView, ListView, TemplateView, UpdateView

from carts.models import Cart
from goods.models import Products
from users.models import Wishlist

from users.forms import UserLoginForm, UserRegistrationForm, UserUpdateForm

from users.utils import get_wishlist_count, get_user_wishlist

class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm

    def get_success_url(self):
        redirect_page = self.request.POST.get('next', None)
        if redirect_page and redirect_page != reverse('user:logout'):
            return redirect_page
        return reverse_lazy('user:profile')
    
    def form_valid(self, form):
        session_key = self.request.session.session_key
        user = form.get_user()

        if user:
            auth.login(self.request, user)

            if session_key:
                new_carts = Cart.objects.filter(session_key=session_key)
                old_carts = Cart.objects.filter(user=user)
                
                for cart in new_carts:
                    existing_cart = old_carts.filter(product=cart.product).first()

                    if existing_cart:
                        existing_cart.quantity += cart.quantity
                        existing_cart.save()
                        cart.delete()
                    else:
                        cart.user = user
                        cart.session_key = None
                        cart.save()

            messages.success(self.request, f"{user.username}, Вы вошли в аккаунт")
            return HttpResponseRedirect(self.get_success_url())
        
    def form_invalid(self, form):
        messages.error(self.request, "Пользователь не найден")
        return super().form_invalid(form)
    
            
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация'
        return context

class UserRegistrationView(CreateView):
    template_name = 'users/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('user:profile')

    @transaction.atomic
    def form_valid(self, form):
        session_key=self.request.session.session_key
        user = form.instance

        if user:
            form.save()
            auth.login(self.request, user)
        if session_key:
            Cart.objects.filter(session_key=session_key).update(user=user, session_key=None)
            
        messages.success(self.request, f"{user.username}, Вы успешно зарегистрировались и вошли в аккаунт")
        return HttpResponseRedirect(self.success_url)
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        return context

class UserProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/profile.html'
    form_class = UserUpdateForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        form.save()
        if self.request.headers.get("x-requested-with") == "XMLHttpRequest":
            messages.success(self.request, f"{self.request.user.username}, Вы успешно обновили профиль")
            return JsonResponse({'success': True})
        return super().form_valid(form)

    def form_invalid(self, form):
        if self.request.headers.get("x-requested-with") == "XMLHttpRequest":
            return JsonResponse({'success': False, 'errors': form.errors}, status=400)
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Профиль пользователя'
        context['body_class'] = 'shop_page'
        return context

class UsersCartView(LoginRequiredMixin, TemplateView):
    template_name = 'users/users_cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Корзина'
        context['show_btn'] = True
        return context

class WishlistAddView(View):
    def post(self, request):
        user = request.user
        if user.is_authenticated:
            product_id = request.POST.get("product_id")
            product = Products.objects.get(id=product_id)
            in_wishlist = request.POST.get("in_wishlist").lower() == "true"
            if not in_wishlist:
                Wishlist.objects.create(user=user, product=product)
                response_data = {
                    'success': True,
                    'message_ajax': "Товар добавлен в избранное",
                    'wishlist_count': get_wishlist_count(request)
                }
            else:
                Wishlist.objects.filter(user=user, product=product).delete()
                wishlist_products = get_user_wishlist(request)
                wishlist_items_html = render_to_string(
                "users/includes/wishlist_items.html", {"wishlist_products": wishlist_products}, request=request)

                response_data = {
                    'success': True,
                    'message_ajax': "Товар удален из избранного",
                    'wishlist_count': get_wishlist_count(request),
                    'wishlist_items_html': wishlist_items_html
                }
        else:
            response_data = {
                'success': False,
                'message_ajax': "Пожалуйста, авторизируйтесь"
            }
        return JsonResponse(response_data)

class WishlistView(LoginRequiredMixin, ListView):
    template_name = 'users/wishlist.html'
    context_object_name = 'wishlist_products'
    paginate_by = 3

    def get_queryset(self):
        return Wishlist.objects.filter(user=self.request.user).order_by('-created_timestamp')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Избранное'
        return context

class CustomLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        username = request.user.username 
        messages.success(request, f"{username}, Вы вышли из аккаунта")
        return super().dispatch(request, *args, **kwargs)

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <!-- Ec login page -->
    <section class="ec-page-content section-space-p">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="section-title">
                        <h2 class="ec-bg-title">Авторизация</h2>
                        <h2 class="ec-title">Авторизация</h2>
                        {% comment %} <p class="sub-title mb-3">Тестовые данные для входа:</p> {% endcomment %}
                    </div>
                </div>
                <div class="ec-login-wrapper">
                    <div class="ec-login-container">
                        <div class="ec-login-form">
                            <form action="{% url "user:login" %}" method="post">
                                {% csrf_token %}

                                {% if request.GET.next %}
                                    <input type="hidden" name="next" value={{ request.GET.next }}>
                                {% endif %}
                                <span class="ec-login-wrap">
                                    <label for="id_username">Введите логин*</label>
                                    <input type="text" name="username" id="id_username" 
                                    value="{% if form.username.value %}{{ form.username.value }}{% endif %}" 
                                    placeholder="Введите логин..." required />
                                </span>
                                <span class="ec-login-wrap">
                                    <label for="id_password">Введите пароль*</label>
                                    <input type="password" name="password" id="id_password"
                                    placeholder="Введите пароль..." required />
                                </span>
                                <span class="ec-login-wrap ec-login-fp">
                                    <label><a href="#">Забыли пароль?</a></label>
                                </span>
                                <span class="ec-login-wrap ec-login-btn">
                                    <button class="btn btn-primary" type="submit">Вход</button>
                                    <a href="{% url "users:registration" %}" class="btn btn-secondary">Регистрация</a>
                                </span>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load phone_tags %}

{% block content %}
<!-- Ec breadcrumb start -->
{% block breadcrumb %}
{% include "includes/breadcrumb.html" %}
{% endblock  %}
<!-- Ec breadcrumb end -->
<!-- User profile section -->
<section class="ec-page-content ec-vendor-uploads ec-user-account section-space-p">
    <div class="container">
        <div class="row">
            <!-- Sidebar Area Start -->
            {% include "users/includes/sidebar.html" %}
            <!-- Sidebar Area End -->

            <div class="ec-shop-rightside col-lg-9 col-md-12">
                <div class="ec-vendor-dashboard-card ec-vendor-setting-card">
                    <div class="ec-vendor-card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="ec-vendor-block-profile">
                                    <div class="ec-vendor-block-img space-bottom-30">
                                        <div class="ec-vendor-block-detail">
                                            <h5 class="name">{{ user.first_name }} {{ user.last_name }}</h5>
                                            <p>( {{ user.username}} )</p>
                                        </div>
                                        <p>Добро пожаловать, <span>{{ user.first_name }}!</span></p>
                                        <p>Здесь вы можете редактировать свой профиль.</p>
                                    </div>
                                    <h5>Информация об аккаунте
                                        <a href="javasript:void(0)" data-link-action="editmodal" title="Редактировать профиль" data-bs-toggle="modal" data-bs-target="#edit_modal"><img src="{% static "assets/images/icons/edit.svg" %}"
                                            class="svg_img pro_svg float-end" alt="edit" />
                                    </h5>

                                    <div class="row">
                                        <div class="col-md-6 col-sm-12">
                                            <div class="ec-vendor-detail-block ec-vendor-block-email space-bottom-30">
                                                <h6>Адрес электронной почты</h6>
                                                <ul>
                                                    <li><b>Email: </b>{{ user.email }}</li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div class="col-md-6 col-sm-12">
                                            <div class="ec-vendor-detail-block ec-vendor-block-contact space-bottom-30">
                                                <h6>Контактный номер</h6>
                                                <ul>
                                                    <li><b>Номер телефона: </b>{% if user.phone_number %}{{ user.phone_number|format_phone_tag }}{% endif %}</li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End User profile section -->
{% endblock %}
{% block modal %}
{% include "users/includes/edit_modal.html" %}
{% endblock modal %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <!-- Start Register -->
    <section class="ec-page-content section-space-p">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="section-title">
                        <h2 class="ec-bg-title">Регистрация</h2>
                        <h2 class="ec-title">Регистрация</h2>
                        <p class="sub-title mb-3">Если у вас уже есть аккаунт, пожалуйста, <a href="{% url 'users:login' %}">войдите</a></p>
                    </div>
                </div>
                <div class="ec-register-wrapper">
                    <div class="ec-register-container">
                        <div class="ec-register-form">
                            <form action="{% url "users:registration" %}" method="post">
                                {% csrf_token %}
                                <span class="ec-register-wrap ec-register-half">
                                    <label for="id_first_name">Имя*</label>
                                    <input type="text" id="id_first_name" 
                                    value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                    name="first_name" placeholder="Введите имя..." required />
                                    {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                    {% endif %}
                                </span>
                                <span class="ec-register-wrap ec-register-half">
                                    <label for="id_last_name">Фамилия*</label>
                                    <input type="text" id="id_last_name"
                                    value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" 
                                    name="last_name" placeholder="Введите фамилию..." required />
                                    {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                    {% endif %}
                                </span>
                                <span class="ec-register-wrap ec-register-half">
                                    <label for="id_username">Логин*</label>
                                    <input type="username" id="id_username"
                                    value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                     name="username" placeholder="Введите логин..." required />
                                    {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                    {% endif %}
                                </span>
                                <span class="ec-register-wrap ec-register-half">
                                    <label for="id_email">Email*</label>
                                    <input type="email" id="id_email"
                                    value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                     name="email" placeholder="Введите email..." required />
                                    {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                    {% endif %}
                                </span>
                                <span class="ec-register-wrap ec-register-half">
                                    <label for="id_phone_number">Номер телефона*</label>
                                    <input type="text" id="id_phone_number"
                                    value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% else %}+7({% endif %}"
                                    name="phone_number" placeholder="Введите номер телефона..."
                                    required />
                                    {% if form.phone_number.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.phone_number.errors }}</div>
                                    {% endif %}
                                </span>
                                <span class="ec-register-wrap ec-register-half">
                                    <label for="id_password1">Пароль*</label>
                                    <input type="password" id="id_password1"
                                    value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                    name="password1" placeholder="Введите пароль..."
                                    required />
                                    {% if form.password1.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                    {% endif %}
                                </span>
                                <span class="ec-register-wrap ec-register-half">
                                    <label for="id_password2">Подтверждение пароля*</label>
                                    <input type="password" id="id_password2"
                                    value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                    name="password2" placeholder="Подтвердите пароль..."
                                    required />
                                    {% if form.password2.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                    {% endif %}
                                </span>
                                <span class="ec-register-wrap ec-register-btn">
                                    <button class="btn btn-primary" type="submit">Регистрация</button>
                                </span>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Register -->
{% endblock %}

users/templates/users/users_cart.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}

{% block content %}
{% user_carts request as carts %}
    <!-- Ec cart page -->
    <section class="ec-page-content section-space-p">
        <div class="container">
            <div class="row">
                <div class="ec-cart-leftside col-lg-8 col-md-12" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {% include "carts/includes/included_cart.html" %}
                    <!-- Закончилась разметка корзины -->
                </div>
                <!-- Sidebar Area Start -->
                <div class="ec-cart-rightside col-lg-4 col-md-12">
                    <div class="ec-sidebar-wrap">
                        <!-- Sidebar Summary Block -->
                        <div class="ec-sidebar-block">
                            <div class="ec-sb-title">
                                <h3 class="ec-sidebar-title">Итог</h3>
                            </div>

                            <div class="ec-sb-block-content">
                                <div class="ec-cart-summary-bottom">
                                    <div class="ec-cart-summary" id="cart-summary-container">
                                        {% include "carts/includes/total.html" %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Sidebar Summary Block -->
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

users/templates/users/wishlist.html
{% extends "base.html" %}
{% load static %}
{% load wishlist_tags %}

{% block content %}

    <!-- User history section -->
    <section class="ec-page-content ec-vendor-uploads ec-user-account wishlist-2 section-space-p">
        <div class="container">
            <div class="row">
                <!-- Sidebar Area Start -->
                {% include "users/includes/sidebar.html" %}
                <!-- Sidebar Area End -->

                <div class="ec-shop-rightside col-lg-9 col-md-12">
                    <div class="ec-vendor-dashboard-card">
                        <div class="ec-vendor-card-header">
                            <h5>{{ title }}</h5>
                            <div class="ec-header-btn">
                                <a class="btn btn-lg btn-primary" href="{% url "catalog:categories" %}">Перейти к покупкам</a>
                            </div>
                        </div>
                        <div class="ec-vendor-card-body">
                            <!-- Разметка таблицы с избранными товарами -->
                            <div class="ec-vendor-card-table" id="wishlist-items-container">
                                {% include "users/includes/wishlist_items.html" %}
                            </div>
                            <!-- Закончилась разметка с избранными товарами -->
                        </div>
                        {% if wishlist_products %}
                        <!-- Ec Pagination Start -->
                        <div class="ec-pro-pagination justify-content-end">
                            <ul class="ec-pro-pagination-inner">
                                <li><a class="next {% if not page_obj.has_previous %} disabled {% endif %}"
                                    href="{% if page_obj.has_previous %}?{% change_params page=page_obj.previous_page_number %}
                                    {% else %}
                                    #
                                    {% endif %}"><i class="ecicon eci-angle-left"></i>&nbspНазад</a></li>
                                    {% for page in page_obj.paginator.page_range %}
                                        {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                                        <li><a class="{% if page_obj.number == page %} active {% endif %}" href="?{% change_params page=page %}">
                                            {{ page }}</a>
                                        </li>
                                        {% endif %}
                                    {% endfor %}

                                <li><a class="next {% if not page_obj.has_next %} disabled {% endif %}" 
                                    href="{% if page_obj.has_next %}?{% change_params page=page_obj.next_page_number %}
                                    {% else %}
                                    #
                                    {% endif %}">Далее <i class="ecicon eci-angle-right"></i></a></li>
                            </ul>
                        </div>
                        <!-- Ec Pagination End -->
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End User history section -->

{% endblock %}